version: '3'
services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_HOST: $DATABASE_HOST
    volumes:
      - psql-db-data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/github.com/RkAirforce/go-next/backend
    links:
      - db
    ports:
      - "$BACKEND_PORT:$CONTAINER_PORT"
  nginx:
    build:
      context: ./backend/nginx
      dockerfile: ./Dockerfile
    ports:
      - "$NGINX_PORT:$CONTAINER_PORT"
    depends_on:
      - backend
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        BACKEND_URL: "http://localhost:$BACKEND_PORT"
    volumes:
      - ./frontend:/$WORKDIR
    command: yarn dev
    ports:
      - "$FRONTEND_PORT:$CONTAINER_PORT"
    depends_on:
      - backend
volumes:
  psql-db-data:
