// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion      string
	LocationInformation string
	Locations           string
	Users               string
}{
	GooseDBVersion:      "goose_db_version",
	LocationInformation: "location_information",
	Locations:           "locations",
	Users:               "users",
}
