// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testLocationInformations(t *testing.T) {
	t.Parallel()

	query := LocationInformations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testLocationInformationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocationInformationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := LocationInformations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocationInformationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LocationInformationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testLocationInformationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := LocationInformationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if LocationInformation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected LocationInformationExists to return true, but got false.")
	}
}

func testLocationInformationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	locationInformationFound, err := FindLocationInformation(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if locationInformationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testLocationInformationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = LocationInformations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testLocationInformationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := LocationInformations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testLocationInformationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	locationInformationOne := &LocationInformation{}
	locationInformationTwo := &LocationInformation{}
	if err = randomize.Struct(seed, locationInformationOne, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}
	if err = randomize.Struct(seed, locationInformationTwo, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = locationInformationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = locationInformationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LocationInformations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testLocationInformationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	locationInformationOne := &LocationInformation{}
	locationInformationTwo := &LocationInformation{}
	if err = randomize.Struct(seed, locationInformationOne, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}
	if err = randomize.Struct(seed, locationInformationTwo, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = locationInformationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = locationInformationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func locationInformationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func locationInformationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *LocationInformation) error {
	*o = LocationInformation{}
	return nil
}

func testLocationInformationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &LocationInformation{}
	o := &LocationInformation{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, locationInformationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize LocationInformation object: %s", err)
	}

	AddLocationInformationHook(boil.BeforeInsertHook, locationInformationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	locationInformationBeforeInsertHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.AfterInsertHook, locationInformationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	locationInformationAfterInsertHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.AfterSelectHook, locationInformationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	locationInformationAfterSelectHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.BeforeUpdateHook, locationInformationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	locationInformationBeforeUpdateHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.AfterUpdateHook, locationInformationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	locationInformationAfterUpdateHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.BeforeDeleteHook, locationInformationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	locationInformationBeforeDeleteHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.AfterDeleteHook, locationInformationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	locationInformationAfterDeleteHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.BeforeUpsertHook, locationInformationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	locationInformationBeforeUpsertHooks = []LocationInformationHook{}

	AddLocationInformationHook(boil.AfterUpsertHook, locationInformationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	locationInformationAfterUpsertHooks = []LocationInformationHook{}
}

func testLocationInformationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLocationInformationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(locationInformationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testLocationInformationToOneLocationUsingLocation(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local LocationInformation
	var foreign Location

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, locationDBTypes, false, locationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Location struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.LocationID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Location().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddLocationHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Location) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := LocationInformationSlice{&local}
	if err = local.L.LoadLocation(ctx, tx, false, (*[]*LocationInformation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Location == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Location = nil
	if err = local.L.LoadLocation(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Location == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testLocationInformationToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local LocationInformation
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, locationInformationDBTypes, false, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := LocationInformationSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*LocationInformation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testLocationInformationToOneSetOpLocationUsingLocation(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a LocationInformation
	var b, c Location

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, locationInformationDBTypes, false, strmangle.SetComplement(locationInformationPrimaryKeyColumns, locationInformationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, locationDBTypes, false, strmangle.SetComplement(locationPrimaryKeyColumns, locationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, locationDBTypes, false, strmangle.SetComplement(locationPrimaryKeyColumns, locationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Location{&b, &c} {
		err = a.SetLocation(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Location != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.LocationInformations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.LocationID != x.ID {
			t.Error("foreign key was wrong value", a.LocationID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.LocationID))
		reflect.Indirect(reflect.ValueOf(&a.LocationID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.LocationID != x.ID {
			t.Error("foreign key was wrong value", a.LocationID, x.ID)
		}
	}
}
func testLocationInformationToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a LocationInformation
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, locationInformationDBTypes, false, strmangle.SetComplement(locationInformationPrimaryKeyColumns, locationInformationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.LocationInformations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testLocationInformationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLocationInformationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := LocationInformationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testLocationInformationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := LocationInformations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	locationInformationDBTypes = map[string]string{`ID`: `integer`, `UserID`: `integer`, `LocationID`: `integer`, `Content`: `character varying`, `CreatedAt`: `timestamp without time zone`, `UpdatedAt`: `timestamp without time zone`}
	_                          = bytes.MinRead
)

func testLocationInformationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(locationInformationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(locationInformationAllColumns) == len(locationInformationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testLocationInformationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(locationInformationAllColumns) == len(locationInformationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &LocationInformation{}
	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, locationInformationDBTypes, true, locationInformationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(locationInformationAllColumns, locationInformationPrimaryKeyColumns) {
		fields = locationInformationAllColumns
	} else {
		fields = strmangle.SetComplement(
			locationInformationAllColumns,
			locationInformationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := LocationInformationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testLocationInformationsUpsert(t *testing.T) {
	t.Parallel()

	if len(locationInformationAllColumns) == len(locationInformationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := LocationInformation{}
	if err = randomize.Struct(seed, &o, locationInformationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LocationInformation: %s", err)
	}

	count, err := LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, locationInformationDBTypes, false, locationInformationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize LocationInformation struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert LocationInformation: %s", err)
	}

	count, err = LocationInformations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
